### ISSUE TITLE
git pull error

### ISSUE THREAD

**Issue by soredake** [vaeth/portage-postsyncd-mv#1]
```
>>> Syncing repository 'rion' into '/var/lib/repos/rion'...
/usr/bin/git pull
remote: Counting objects: 625, done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 625 (delta 486), reused 625 (delta 486), pack-reused 0
Receiving objects: 100% (625/625), 88.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (486/486), completed with 365 local objects.
From https://github.com/rion-overlay/rion-overlay
   0ad2494..f76da71  master     -> origin/master
Updating b1117b0..f76da71
error: Your local changes to the following files would be overwritten by merge:
	Documentation/generate-psi-plugins-ebuilds.sh
	metadata/md5-cache/app-admin/openwbem-3.2.2
	metadata/md5-cache/app-admin/sblim-sfcb-1.3.15
	metadata/md5-cache/app-admin/sblim-sfcb-1.3.16
	metadata/md5-cache/app-admin/wsl-0.2.1
	metadata/md5-cache/app-emulation/aqemu-0.9.2
	metadata/md5-cache/app-laptop/clevo-wmi-9999
	metadata/md5-cache/app-misc/a4tool-0.1_beta1
	metadata/md5-cache/app-misc/anki-2.0.36
	metadata/md5-cache/app-misc/anki-9999
Please commit your changes or stash them before you merge.
Aborting
!!! git pull error in /var/lib/repos/rion
```

**Comment by vaeth** [comment]
This is a portage error which occurs before anything from portage-postsyncd is called.
I am nerved by this portage bug as much as you are, but you have to bug the portage people about it:
They decided to remove the working solution from https://bugs.gentoo.org/show_bug.cgi?id=552814 with carefully rebuilding the index and git reset, because it is slower, although they know that a plain "git pull" breaks for certain users quite frequently.

**Comment by soredake** [comment]
What commit do i need to revert to fix git pull? https://gitweb.gentoo.org/proj/portage.git/commit/pym/portage/sync/modules/git/git.py?id=f77fcd6b0b4ebb49ca62f5767cd5c931127c3dbb or https://gitweb.gentoo.org/proj/portage.git/commit/pym/portage/sync/modules/git/git.py?id=d075422a8902617833ec945d94beb0bb334d44c9 ?

**Comment by vaeth** [comment]
Both (the former in any case, the latter if you use e.g. overlay+squashfs).
However, I think that you cannot cleanly revert these.
I am using an sed command to patch portage during installation:
https://github.com/vaeth/portage-env-mv/blob/master/env/sys-apps/portage
