### ISSUE TITLE
Version 8.2 now prints errors while sync'ing.

### ISSUE THREAD

**Issue by waptaff** [vaeth/portage-postsyncd-mv#5]
The new `--reinitialize` option passed to `q` does not exist in `=app-portage/portage-utils-0.80_pre20190610`, so when doing an upstream sync, I get something like the following for the main repo and all overlays:

```
 * Calling q --reinitialize for the chaoslab repository
q: unrecognized option '--reinitialize=/var/lib/layman/chaoslab'
Usage: q <applet> <args>  : invoke a portage utility applet

Currently defined applets:
```
[…]

It appears the `--reinitialize` option was removed with this commit on Apr 25th, 2019: https://gitweb.gentoo.org/proj/portage-utils.git/commit/?id=1cd2f17f673a790caaa967341b7f2b1072968e51

**Comment by vaeth** [comment]
Thanks. Should be fixed in v8.3.
